### ISSUE TITLE
Schemas with default values for fixed and bytes fields do not parse.

### ISSUE THREAD

**Issue by TikhonJelvis** [GaloisInc/avro#18]
A schema containing a record with the following field:

```
{ "name": "binary",
        "type": {
          "type" : "fixed",
          "name" : "FixedField",
          "size" : 1
        },
        "default": "\u0000"
      }
```

will fail to parse because `parseAvroJSON` does not handle parsing JSON strings into `Fixed` or `Bytes` values:

```
Could not resolve type 'string' with expected type: Fixed {name = "FixedField", namespace = Nothing, aliases = [], size = 1}
```

The same problem for a field with type "bytes":

```
Could not resolve type 'string' with expected type: Bytes
```

**Comment by TikhonJelvis** [comment]
I have a couple of failing test cases for this and I'm pretty sure I know how to fix it, but I figure I'd throw up an issue while I start working on a PR for it.

**Comment by AlexeyRaga** [comment]
Yes, `default` is a bit of a gray area. We have never used it until recently, and I fixed a bug regarding `default=null` a couple of days ago, so there may be more corner cases about it.

**Comment by TikhonJelvis** [comment]
Luckily, the code for dealing with defaults is basically a subset of the code for dealing with JSON-encoded values, so I'll be adding tests and fixing issues around defaults as part of exposing the JSON functionality.

I'm actually already part of the way through a patch for this issue. I've just run into a problem with the TH deriving code that needs debugging.

**Comment by TikhonJelvis** [comment]
Okay, I believe this is fixed now.
