### ISSUE TITLE
Names and namespaces are not handled correctly.

### ISSUE THREAD

**Issue by TikhonJelvis** [GaloisInc/avro#19]
I see three separate problems with how names are currently handled:

  * a `namespace` of `Nothing` is semantically the same as `Just ""`
  * `name` and `namespace` should be unified into `TypeName` because we should never compare names without considering the namespaces
  * namespaces should be inferred following the rather ugly rules in the Avro specification

The first issue is a problem because `Nothing /= Just ""` even though they mean the same thing. Using `Text` instead of `Maybe Text` would remove this weird edgecase while also making the code simpler (including some of the Template Haskell code I'm working on).

The second issue is that equality between names in Avro is defined on the "fullname" (ie name + namespace). The easiest way to make this work in the Haskell code is moving `namespace` into `TypeName`:

```
data TypeName = TN
  { name      :: Text
  , namespace :: Text
  }
```

The third issue is something that should be handled when parsing or validating schemas: we need to infer namespaces following some tedious rules laid out in the Avro protocol:

> In record, enum and fixed definitions, the fullname is determined in one of the following ways:
>   * A name and namespace are both specified. For example, one might use "name": "X", "namespace": "org.foo" to indicate the fullname org.foo.X.
>  * A fullname is specified. If the name specified contains a dot, then it is assumed to be a fullname, and any namespace also specified is ignored. For example, use "name": "org.foo.X" to indicate the fullname org.foo.X.
>  * A name only is specified, i.e., a name that contains no dots. In this case the namespace is taken from the most tightly enclosing schema or protocol. For example, if "name": "X" is specified, and this occurs within a field of the record definition of org.foo.Y, then the fullname is org.foo.X. If there is no enclosing namespace then the null namespace is used.
>
> References to previously defined names are as in the latter two cases above: if they contain a dot they are a fullname, if they do not contain a dot, the namespace is the namespace of the enclosing definition.

Adding code to infer namespaces sounds like a real pain. I think it would be reasonable to fix the first two issues and punt on the third one, at least for now—people can always work around this by always specifying explicit namespaces for named types.

Addressing these issues would involve some pretty broad breaking changes to the library. I'm happy to work on it at some point, but I'd love to hear thoughts about whether it's even worth doing and what the best approach would be.

**Comment by TikhonJelvis** [comment]
Another option is to get rid of the `namespace` field altogether and always fold the namespace into the `name` field. This way names are just strings that can be compared and all the namespace nonsense is handled when we parse or define schemas.

**Comment by AlexeyRaga** [comment]
@TikhonJelvis can this issue be closed or you still have something in mind around it?
