### ISSUE TITLE
Release version of package with JSON module

### ISSUE THREAD

**Issue by TikhonJelvis** [GaloisInc/avro#23]
Do we need anything else before we can release a version of `avro` to Hackage with the new JSON module exposed?

I believe I made some backwards-incompatible changes to how schemas are parsed (to match the Avro specification), so the new version should be 0.3.0.0 or something.

**Comment by AlexeyRaga** [comment]
I'll do it

**Comment by AlexeyRaga** [comment]
@TikhonJelvis before we release it, can you please have a look at the CI here?
It looks like one of your tests is failing:
https://circleci.com/gh/GaloisInc/avro/7

**Comment by TikhonJelvis** [comment]
Oh boy, looks like this is a known issue with Stack and data-files: https://github.com/commercialhaskell/stack/issues/548

:/

I am not sure about the best way to fix this because I don't use Stack. Do you have any suggestions? Maybe switching to this `file-embed` package?

**Comment by AlexeyRaga** [comment]
OK, I have released `0.3.0.0`!
Thanks a lot for making it happen, @TikhonJelvis !
