### ISSUE TITLE
Defaults for Union types are not encoded/decoded correctly

### ISSUE THREAD

**Issue by AlexeyRaga** [GaloisInc/avro#25]
@TikhonJelvis I have bumped into an issue where default values for union types are not encoded/decoded in Schema in a way that they can be respected by decoding functionality.

For this schema:
```
{
        "type": "record",
        "name": "Inner",
        "fields": [
          { "name": "id", "type": "int" },
          { "name": "smell", "type": ["null", "string"], "default": null }
        ]
}
```

the expected Haskell representation would be:
```
Record 
  { name = "Inner"
  , namespace = Nothing
  , aliases = []
  , doc = Nothing
  , order = Just Ascending
  , fields = 
      [ Field 
          { fldName = "id"
          , fldAliases = []
          , fldDoc = Nothing
          , fldOrder = Just Ascending
          , fldType = Int
          , fldDefault = Nothing
          }
      , Field 
          { fldName = "smell"
          , fldAliases = []
          , fldDoc = Nothing
          , fldOrder = Just Ascending
          , fldType = Union {options = Null :| [String], unionLookup = <function>}, fldDefault = Just (Union (Null :| [String]) Null Null)}
      ]
  }
```

Note that the `fldDefault` is annotated with its type of `Union Null String`.

However the current implementation gives me this:
```
Record 
  { name = "Inner"
  , namespace = Nothing
  , aliases = []
  , doc = Nothing
  , order = Just Ascending
  , fields = 
      [ Field 
          { fldName = "id"
          , fldAliases = []
          , fldDoc = Nothing
          , fldOrder = Just Ascending
          , fldType = Int
          , fldDefault = Nothing
          }
      , Field 
          { fldName = "smell"
          , fldAliases = []
          , fldDoc = Nothing
          , fldOrder = Just Ascending
          , fldType = Union {options = Null :| [String], unionLookup = <function>}, fldDefault = Just Null}
      ]
  }
```
Which doesn't annotate the union type for the default value.

Looking at the code I see that it has been done deliberately.
Is there anything that I am missing or should we fix the type annotation back?

**Comment by AlexeyRaga** [comment]
The error that I am currently getting is this:
```
Error "Unexpected value when decoding for 'Maybe a': Null"
```
Which is correct in a way, because `Null` is not of type `Union`.

**Comment by TikhonJelvis** [comment]
I changed the union code to reflect the fact that the default value for a union has to be from the *first* branch of the union. It looks like this is an unintended consequence of that change.

I can't think of a way to fix this without special-casing unions one way or another. The simplest thing is probably wrapping the `fldDefault` value in the appropriate `Union` when building the `Schema` record.

**Comment by AlexeyRaga** [comment]
I think we can fix type annotation back and it'll work again.
From what I see now the change is somewhere between `304ada7` (which works) and `15400f3` (which doesn't work).

I'll branch off `304ada7` to create `0.2.1.2` release (because I need to fix another unrelated bug for de-conflicting schemas) and then will try tracking it down and figuring out how to preserve the annotation.

Any help/advice is appreciated! :)

**Comment by TikhonJelvis** [comment]
I can take a quick stab at fixing it for the `0.3.*` version of the package.

I would like to preserve the new behavior because the old version did not match the Avro specification and the way it handled the logic caused me some problems. (I'd have to root around a bit for the exact details, but I was having trouble when it failed to match a `NamedType` against the complex type with the corresponding name.)

On a related note, I think it would be really helpful to continue making tags like `v0.3.0.0` for every release. It makes navigating through old version much easier, like finding which commit `0.2.1.1` was released at.

**Comment by AlexeyRaga** [comment]
Tags are now done automatically every time CI detects a version change in the cabal file :) I think it'll continue to work.
