### ISSUE TITLE
Publish on Hackage

### ISSUE THREAD

**Issue by AlexeyRaga** [GaloisInc/avro#3]
Can it be published on Hackage?

**Comment by TomMD** [comment]
I can, but would you be interested in pushing it to hackage?   I don't have sufficient time to maintain it to a comfortable level and I regard hackage as a commitment to the community.

**Comment by AlexeyRaga** [comment]
Potentially yes. I am just starting using it seriously in production, so I may want/need to put some effort to it anyway (although I still hope that it would "just work" :))).
Let's come back to this matter once again a bit later :)
