### ISSUE TITLE
Fails to build with Eta

### ISSUE THREAD

**Issue by Jyothsnasrinivas** [GaloisInc/avro#42]
I'm trying to build the avro-0.3.2.0 with Eta and it fails with the following error:

```
[16 of 17] Compiling Data.Avro.Deriving
src/Data/Avro/Deriving.hs:335:74: error:
    Not in scope: ‘e’
    In the Template Haskell quotation
      [| ($(mkText k), $(mkDefaultValue v)) e |]
    |
335 |         mkKVPair (k, v)         = [e| ($(mkText k), $(mkDefaultValue v)) e|]
```

I've made the following change to the line https://github.com/GaloisInc/avro/blob/master/src/Data/Avro/Deriving.hs#L335 to 
```haskell
mkKVPair (k, v)         = [e| ($(mkText k), $(mkDefaultValue v)) |]
```

Will this maintain the original intent?

**Comment by alexbiehl** [comment]
Uh. Corner case in GHC? `e` is no free variable in scope here. Care to make a quick PR?

**Comment by Jyothsnasrinivas** [comment]
@alexbiehl Yes, I felt the same. I wanted to be sure if there was any GHC-specific behaviour that I wasn't aware of.  Submitted the pull request.
