### ISSUE TITLE
`buildTypeEnvironment` doesn't work properly with maps

### ISSUE THREAD

**Issue by TikhonJelvis** [GaloisInc/avro#61]
`buildTypeEnvironment` on older versions of the package doesn't handle maps properly.

```
case ty of
        Record {..} -> mk name aliases namespace ++ concatMap (go . fldType) fields
        Enum {..}   -> mk name aliases namespace
        Union {..}  -> concatMap go options
        Fixed {..}  -> mk name aliases namespace
        Array {..}  -> go item
        _           -> []
```

This `case` should also recurse on `Map {..}`:

```
    Map {..} -> go values
```

This leads to errors on schemas that define a named type in a map and then refer to it:

```
{
  "name" : "Foo",
  "type" : "record",
  "fields" : [
    {
      "name" : "bar",
      "type" : {
        {
          "type" : "map",
          "values" : {
            "name" : "Bar",
            "type" : "record",
            "fields" : []
          }
        }
      }
    },
    {
      "name" : "bar2",
      "type" : "Bar"
    }
  ]
}
```

Decoding an object with this schema will result in an error about the type `"Bar"` not being in scope.

It looks like I actually fixed this in my [namespace PR][pr] (although I don't remember doing that explicitly). The minimum we can do to fix this is release a new version with that PR included (it has already been merged on master.)

This bug isn't specific to namespaces, so it might be worth releasing bug-fixes for older versions of `avro` on Hackage as well.

[pr]: https://github.com/GaloisInc/avro/pull/52/files#diff-c706ddb51af8ea184305059c27c103daL533

**Comment by TikhonJelvis** [comment]
Looks like the newest version of the code doesn't work with arrays *or* maps. I'm also having issues with the new `extractBindings` function missing other kinds of nested types.

This is a bit troubling because it means the package won't work with perfectly valid schemas. I've put together a PR that fixes this problem and includes tests to ensure the logic is correct.

**Comment by AlexeyRaga** [comment]
@TikhonJelvis is it fixed now? Can this  issue be closed?

**Comment by TikhonJelvis** [comment]
@AlexeyRaga Yes, this should be fixed now. Thanks!
