### ISSUE TITLE
0.3.6.0 API breaking change

### ISSUE THREAD

**Issue by imalsogreg** [GaloisInc/avro#64]
Hello! 0.3.6.0 adds a new field to the `TN` constructor in `Data.Avro.Schema.TypeName`.

This change breaks downstream users of that constructor - would you be open to making a new release called 0.4 (no code change, just version bump), to match the PVP convention? and maybe even further, marking 0.3.6.0 and 0.3.6.1 as deprecated?

I'm not blocked on this personally, but it would likely help other users.

**Comment by AlexeyRaga** [comment]
Done, thanks!

**Comment by imalsogreg** [comment]
Thank you!
