### ISSUE TITLE
Why use entropy

### ISSUE THREAD

**Issue by AlexeyRaga** [GaloisInc/avro#8]
Hi @TomMD,

Just a question. I see that you use `entropy` package for generating "The 16-byte, randomly-generated sync marker".
Can you explain why `entropy` and why "standard" `random` cannot be used?

**Comment by TomMD** [comment]
The random package and its `StdGen` is a terrible random number generator and uses bad seed values.  I expect the sync marker is 16 random bytes out of an expectation it will not repeat (i.e. a nonce), but I'm not confident that expectation would be met if I used `random`.

**Comment by AlexeyRaga** [comment]
Thanks! 
Do you have anything in mind that I can use instead of `entropy` that doesn't depend on `unix` and C code?
The reason I am asking is that I wanted to compile this package for `eta` (ghc port for jvm), and obviously C bits don't compile that easily. 
There is a way to work it around, but I wanted to ask first if you know something Haskell-native that we use instead?

**Comment by TomMD** [comment]
Hurm, I can think of a number of RNGs but the issue here is really the seed.  There isn't a Haskell native seed that I know of - it's sort of a system responsibility to provide a seed.

How do you usually get random numbers (secure seed values) in `eta`? Keep in mind I don't know a thing about it.  Can't we just patch `entropy` to support eta better?

**Comment by AlexeyRaga** [comment]
Yes, that is what meant when I said that there is a workaround: patching `entropy`, or even the `avro` for `eta`.
`Eta` has the idea of "patches" that are applied automatically when a library gets pulled from Hackage. It is its way of dealing with these kind of issues: wherever a Haskell lib uses C, there can be a patch which, for example, uses JVM functions instead of C ones.

For example, `tf-random` is patched like that: https://github.com/typelead/eta-hackage/blob/master/patches/tf-random-0.5.patch
Then when I pull `tf-random` from Hackage, Eta automatically applies this patch.

I can try doing it for `entropy`, or even for `avro` itself (replacing that 16 bytes random hash with whatever the Java Avro uses as a generator).
I just wanted to see if there is anything you could suggest that could be used and be would be correct.

**Comment by TomMD** [comment]
For this use I'm comfortable switching to tf-random if that would make your
life easier.  Thoughts?

**Comment by AlexeyRaga** [comment]
We are not using containers at all (we rather read/wrire Kafka) so I am OK with `tf-random`.
I'll make a change if there is an agreement. It is going to be in my second PR soon.

**Comment by imalsogreg** [comment]
I too am interested in replacing `entropy` with `tf-random`! I want to compile `avro` with ghcjs and run it in a browser, meaning I need a library without system access. Will get a quick PR up.
